
CREATE TABLE IF NOT EXISTS `t_bag_10` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_11` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_12` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_13` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_14` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_15` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_16` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_17` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_18` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_19` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_20` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_21` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_22` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_23` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_24` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_25` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_26` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_27` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_28` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_29` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_30` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_31` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_32` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_33` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_34` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_35` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_36` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_37` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_38` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_39` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_40` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_41` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_42` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_43` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_44` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_45` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_46` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_47` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_48` LIKE `t_bag_0`;

CREATE TABLE IF NOT EXISTS `t_bag_49` LIKE `t_bag_0`;